on:
  pull_request:
    branches:
      - main
  pull_request_review:
    branches:
      - main

jobs:
  inspect:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 1.8 for x64
        uses: actions/setup-java@v4
        with:
          java-version: "1.8"
          distribution: "temurin"
          architecture: x64

      - run: ant -noinput -buildfile build.xml
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build/jar
